pipeline {
    agent any

    environment {
        // Environment variables are securely managed in Jenkins
        // These will be retrieved from the Jenkins credentials store
        EPUB_READWISE_TOKEN = credentials('EPUB_READWISE_TOKEN')
        EPUB_FTP_PASS = credentials('EPUB_FTP_PASS')
        // Non-secret variables can be defined here
        GAS_ENDPOINT_EPUBS_PROCESSED_TRACKER = credentials('GAS_ENDPOINT_EPUBS_PROCESSED_TRACKER')
    }

    stages {
        stage('Setup Environment and Dependencies') {
            steps {
                sh '''
                    # Check for python3
                    python3 --version

                    # Create a virtual environment
                    python3 -m venv venv

                    # Activate the virtual environment using the '.' command
                    . venv/bin/activate

                    # Install Python dependencies from requirements.txt
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Script') {
            steps {
                sh '''
                    # Use the virtual environment's python and add kepubify to PATH
                    export PATH="/usr/local/bin:$PATH"
                    . venv/bin/activate
                    python3 readwise_to_epub/readwise_to_epub.py
                '''
            }
        }
    }
}