pipeline {
    agent any

    environment {
        // Environment variables are securely managed in Jenkins
        // These will be retrieved from the Jenkins credentials store
        EPUB_READWISE_TOKEN = credentials('EPUB_READWISE_TOKEN')
        EPUB_FTP_PASS = credentials('EPUB_FTP_PASS')
        // Non-secret variables can be defined here
        GAS_ENDPOINT_EPUBS_PROCESSED_TRACKER = credentials('GAS_ENDPOINT_EPUBS_PROCESSED_TRACKER')
    }

    stages {
        stage('Install System Dependencies') {
            steps {
                script {
                    // Update package list and install wget. This requires Jenkins user to have sudo privileges.
                    sh 'sudo apt-get update'
                    sh 'sudo apt-get install -y wget'
                }
            }
        }
        stage('Install kepubify') {
            steps {
                sh '''
                    # Download the correct version of kepubify for Linux 64-bit
                    wget https://github.com/pgaskin/kepubify/releases/download/v4.0.4/kepubify-linux-64bit

                    # Make the downloaded file executable
                    chmod +x kepubify-linux-64bit
                    
                    # Move the executable to a directory in the PATH
                    # Note: /usr/local/bin is a standard location
                    # You may need to use 'sudo' if the jenkins user doesn't have permissions
                    sudo mv kepubify-linux-64bit /usr/local/bin/kepubify

                    # Verify installation
                    kepubify --version
                '''
            }
        }
        stage('Setup Environment and Dependencies') {
            steps {
                sh '''
                    # Check for python3
                    python3 --version

                    # Create a virtual environment
                    python3 -m venv venv

                    # Activate the virtual environment using the '.' command
                    . venv/bin/activate

                    # Install Python dependencies from requirements.txt
                    pip install -r readwise_to_epub/requirements.txt
                '''
            }
        }

        stage('Run Script') {
            steps {
                sh '''
                    # Use the virtual environment's python and add kepubify to PATH
                    export PATH="/usr/local/bin:$PATH"
                    . venv/bin/activate
                    python3 readwise_to_epub/readwise_to_epub.py
                '''
            }
        }
    }
}